version: '3.5'

networks:
    shared-network:
        external: true

volumes:
    fuseki-volume-1:
    fuseki-volume-2:
    fuseki-volume-3:

services:
    traefik:
        command:
            - --api
            - --docker
        expose:
            - 8080
        image: traefik:alpine
        labels:
            - traefik.enable=true
            - traefik.frontend.rule=Host:traefik.${HOST}
            - traefik.port=8080
            # - traefik.docker.network=shared-network
        networks:
            - shared-network
        ports:
            - "80:80"
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./traefik.toml:/etc/traefik/traefik.toml
    aec-app:
        build:
            context: ../app
            dockerfile: Dockerfile
        command: >
            sh -c "cd /usr/src/app; node_modules/.bin/ng serve --host 0.0.0.0 --poll 1 --disableHostCheck"
        container_name: aec_app
        depends_on:
            - traefik
            - aec-api
        labels:
            - traefik.enable=true
            - traefik.frontend.rule=Host:${HOST}
            - traefik.port=4200
            - traefik.docker.network=shared-network
        networks:
            - shared-network
        ports:
            - 4200:4200
        volumes:
            - ../app/e2e:/usr/src/app/e2e
            - ../app/src:/usr/src/app/src
            - ../app/.editorconfig:/usr/src/app/.editorconfig
            - ../app/angular.json:/usr/src/app/angular.json
            - ../app/browserslist:/usr/src/app/browserslist
            - ../app/karma.conf.js:/usr/src/app/karma.conf.js
            - ../app/tsconfig.app.json:/usr/src/app/tsconfig.app.json
            - ../app/tsconfig.json:/usr/src/app/tsconfig.json
            - ../app/tsconfig.spec.json:/usr/src/app/tsconfig.spec.json
            - ../app/tslint.json:/usr/src/app/tslint.json
    aec-api:
        build: ../api
        command: >
            sh -c "cd /usr/src/app; node_modules/.bin/nodemon -L index.js"
        container_name: aec_api
        depends_on:
            - traefik
        ports:
            - 3000:3000
        labels:
            - traefik.enable=true
            - traefik.frontend.rule=Host:api.${HOST}
            - traefik.port=3000
            - traefik.docker.network=shared-network
        environment:
            - HOSTNAME=${HOST}
            - DEBUG=true
            - PORT=3000
        networks:
            - shared-network
        volumes:
            - ../api/routes:/usr/src/app/routes
            - ../api/methods:/usr/src/app/methods
            - ../api/index.js:/usr/src/app/index.js
    aec-fuseki-1:
        command: >
            sh -c
            "
            for db in /fuseki/dbs/*; do
            file=$$(basename $$db);
            name=$$(basename $${db%%.*});
            if [ ! -d /fuseki/databases/_$$name ];
            then
                mkdir -p /fuseki/configuration
                cp /fuseki/reasoning_config.ttl /fuseki/configuration/$$name.ttl
                sed -i 's/<db>/'$$name'/g' /fuseki/configuration/$$name.ttl
                mkdir -p /fuseki/databases/$$name
                /jena-fuseki/tdbloader --loc=/fuseki/databases/_$$name /fuseki/dbs/$$file
                cp -R /fuseki/databases/_$$name/* /fuseki/databases/$$name
            fi;
            done;
            /jena-fuseki/fuseki-server
            "
        container_name: aec_fuseki_1
        image: stain/jena-fuseki
        restart: on-failure
        ports:
            - 3030:3030
        expose:
            - 3030
        environment:
            - JVM_ARGS=-Xmx10g
        volumes:
            - fuseki-volume-1:/fuseki
            - ./shiro.ini:/fuseki/shiro.ini
            - ./fuseki/aec-fuseki-1:/fuseki/dbs
            - ./fuseki/reasoning_config.ttl:/fuseki/reasoning_config.ttl
        networks:
            - shared-network
    aec-fuseki-2:
        command: >
            sh -c
            "
            for db in /fuseki/dbs/*; do
            file=$$(basename $$db);
            name=$$(basename $${db%%.*});
            if [ ! -d /fuseki/databases/_$$name ];
            then
                mkdir -p /fuseki/configuration
                cp /fuseki/reasoning_config.ttl /fuseki/configuration/$$name.ttl
                sed -i 's/<db>/'$$name'/g' /fuseki/configuration/$$name.ttl
                mkdir -p /fuseki/databases/$$name
                /jena-fuseki/tdbloader --loc=/fuseki/databases/_$$name /fuseki/dbs/$$file
                cp -R /fuseki/databases/_$$name/* /fuseki/databases/$$name
            fi;
            done;
            /jena-fuseki/fuseki-server
            "
        container_name: aec_fuseki_2
        image: stain/jena-fuseki
        restart: on-failure
        ports:
            - 3031:3030
        expose:
            - 3031
        environment:
            - JVM_ARGS=-Xmx10g
        volumes:
            - fuseki-volume-2:/fuseki
            - ./shiro.ini:/fuseki/shiro.ini
            - ./fuseki/aec-fuseki-2:/fuseki/dbs
            - ./fuseki/reasoning_config.ttl:/fuseki/reasoning_config.ttl
        networks:
            - shared-network
    aec-fuseki-3:
        command: >
            sh -c
            "
            for db in /fuseki/dbs/*; do
            file=$$(basename $$db);
            name=$$(basename $${db%%.*});
            if [ ! -d /fuseki/databases/_$$name ];
            then
                mkdir -p /fuseki/configuration
                cp /fuseki/reasoning_config.ttl /fuseki/configuration/$$name.ttl
                sed -i 's/<db>/'$$name'/g' /fuseki/configuration/$$name.ttl
                mkdir -p /fuseki/databases/$$name
                /jena-fuseki/tdbloader --loc=/fuseki/databases/_$$name /fuseki/dbs/$$file
                cp -R /fuseki/databases/_$$name/* /fuseki/databases/$$name
            fi;
            done;
            /jena-fuseki/fuseki-server
            "
        container_name: aec_fuseki_3
        image: stain/jena-fuseki
        restart: on-failure
        ports:
            - 3032:3030
        expose:
            - 3032
        environment:
            - JVM_ARGS=-Xmx10g
        volumes:
            - fuseki-volume-3:/fuseki
            - ./shiro.ini:/fuseki/shiro.ini
            - ./fuseki/aec-fuseki-3:/fuseki/dbs
            - ./fuseki/reasoning_config.ttl:/fuseki/reasoning_config.ttl
        networks:
            - shared-network
