debug = false
insecureSkipVerify= true

logLevel = "WARN"
defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
[retry]

[api]
dashboard = true
  [api.statistics]
  recentErrors = 20

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
# Only expose services that are enabled explicitly
exposedbydefault = false