FROM node:11
WORKDIR /usr/src/app
COPY ./package.json /usr/src/app/package.json
RUN npm install

# WORKDIR /usr/src/app


# RUN npm install
# RUN npm install nodemon -g

# EXPOSE 8080

# CMD ["nodemon", "-L", "server.js"]
#CMD ["npm", "run", "start"]
